
version: "2.1"
services:
  mongo-sample-data:
    build: ./infra
    ports:
      - "27017:27017"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:27017"]
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      NODE_ENV: production
      
  webserver:
    build: ./
    depends_on:
      mongo-sample-data:
        condition: service_healthy
    ports:
      - "3003:3003"
    links:
      - mongo-sample-data 
