export const ADD_GENRE =  'ADD_GENRE'
export const FETCH_SONGS =  'FETCH_SONGS'
export const CHANGE_SKIP =  'CHANGE_SKIP'
export const RESET_SKIP =  'RESET_SKIP'
export const CHANGE_GENRE_ID =  'CHANGE_GENRE_ID'
export const ADD_SONG =  'ADD_SONG'
export const ERROR ='ERROR'
