export const ADD_TYPE =  'ADD_TYPE'
export const FETCH_SONGS =  'FETCH_SONGS'
export const CHANGE_SKIP =  'CHANGE_SKIP'
export const RESET_SKIP =  'RESET_SKIP'
export const CHANGE_TYPE_ID =  'CHANGE_TYPE_ID'
export const ADD_SONG =  'ADD_SONG'
